version: '3.9'

services:
    mongo_db:
        container_name: mongo_db_container
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        volumes:
            - mongo_db:/data/db

    api:
        container_name: nodejs_api_container
        build: .
        ports:
            - 3000:3000
        environment:
            PORT: 3000
            MONGO_DB_URI: 'mongodb://mongo_db:27017/node-challenge'
            JWT_SECRET: 'NNj1QPNHkdkSNuj03RaJbNpmuwkuw'
        depends_on:
            - mongo_db

volumes:
    mongo_db: {}
